<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ACoqUn1' shared service.

return $this->privates['.service_locator.ACoqUn1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repository' => ['privates', 'App\\Repository\\ImagePostRepository', 'getImagePostRepositoryService.php', true],
], [
    'repository' => 'App\\Repository\\ImagePostRepository',
]);
