<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oXryCJz' shared service.

return $this->privates['.service_locator.oXryCJz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ImagePostController::create' => ['privates', '.service_locator.3verMdE', 'get_ServiceLocator_3verMdEService.php', true],
    'App\\Controller\\ImagePostController::delete' => ['privates', '.service_locator.10xTIct', 'get_ServiceLocator_10xTIctService.php', true],
    'App\\Controller\\ImagePostController::getItem' => ['privates', '.service_locator.bYI0OVI', 'get_ServiceLocator_BYI0OVIService.php', true],
    'App\\Controller\\ImagePostController::list' => ['privates', '.service_locator.ACoqUn1', 'get_ServiceLocator_ACoqUn1Service.php', true],
    'App\\Controller\\ImagePostController:create' => ['privates', '.service_locator.3verMdE', 'get_ServiceLocator_3verMdEService.php', true],
    'App\\Controller\\ImagePostController:delete' => ['privates', '.service_locator.10xTIct', 'get_ServiceLocator_10xTIctService.php', true],
    'App\\Controller\\ImagePostController:getItem' => ['privates', '.service_locator.bYI0OVI', 'get_ServiceLocator_BYI0OVIService.php', true],
    'App\\Controller\\ImagePostController:list' => ['privates', '.service_locator.ACoqUn1', 'get_ServiceLocator_ACoqUn1Service.php', true],
], [
    'App\\Controller\\ImagePostController::create' => '?',
    'App\\Controller\\ImagePostController::delete' => '?',
    'App\\Controller\\ImagePostController::getItem' => '?',
    'App\\Controller\\ImagePostController::list' => '?',
    'App\\Controller\\ImagePostController:create' => '?',
    'App\\Controller\\ImagePostController:delete' => '?',
    'App\\Controller\\ImagePostController:getItem' => '?',
    'App\\Controller\\ImagePostController:list' => '?',
]);
