<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bYI0OVI' shared service.

return $this->privates['.service_locator.bYI0OVI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'imagePost' => ['privates', '.errored..service_locator.bYI0OVI.App\\Entity\\ImagePost', NULL, 'Cannot autowire service "debug.traced.messenger.bus.default.inner": it references class "App\\Entity\\ImagePost" but no such service exists.'],
], [
    'imagePost' => 'App\\Entity\\ImagePost',
]);
