<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.messenger_consume_messages' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php';

$this->privates['console.command.messenger_consume_messages'] = $instance = new \Symfony\Component\Messenger\Command\ConsumeMessagesCommand(($this->privates['messenger.routable_message_bus'] ?? $this->load('getMessenger_RoutableMessageBusService.php')), ($this->privates['messenger.receiver_locator'] ?? $this->load('getMessenger_ReceiverLocatorService.php')), ($this->privates['monolog.logger.messenger'] ?? $this->load('getMonolog_Logger_MessengerService.php')), [0 => 'async'], new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'async' => ['privates', 'messenger.retry.multiplier_retry_strategy.async', 'getMessenger_Retry_MultiplierRetryStrategy_AsyncService.php', true],
], [
    'async' => '?',
]), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setCachePoolForRestartSignal(($this->privates['cache.messenger.restart_workers_signal'] ?? $this->getCache_Messenger_RestartWorkersSignalService()));
$instance->setName('messenger:consume');
$instance->setAliases([0 => 'messenger:consume-messages']);

return $instance;
