<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Photo\PhotoFileManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Photo/PhotoFileManager.php';

return $this->privates['App\\Photo\\PhotoFileManager'] = new \App\Photo\PhotoFileManager(($this->privates['photo.filesystem'] ?? $this->load('getPhoto_FilesystemService.php')), '/uploads/images');
