<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.messenger.handler_descriptor.KV7J8Zf' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
include_once $this->targetDirs[3].'/src/MessageHandler/DeleteImagePostHandler.php';

return $this->privates['.messenger.handler_descriptor.KV7J8Zf'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\DeleteImagePostHandler(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['message_bus'] ?? $this->getMessageBusService())), []);
