<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.transport.doctrine.factory' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Doctrine/DoctrineTransportFactory.php';

return $this->privates['messenger.transport.doctrine.factory'] = new \Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory(($this->services['doctrine'] ?? $this->getDoctrineService()));
