<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.receiver_locator' shared service.

return $this->privates['messenger.receiver_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService.php', true],
    'messenger.transport.async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService.php', true],
], [
    'async' => '?',
    'messenger.transport.async' => '?',
]);
