<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.retry.multiplier_retry_strategy.async' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Retry/RetryStrategyInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Retry/MultiplierRetryStrategy.php';

return $this->privates['messenger.retry.multiplier_retry_strategy.async'] = new \Symfony\Component\Messenger\Retry\MultiplierRetryStrategy(3, 1000, 2, 0);
